<?php
$baseQuery = ['q'=>$filters['q'],'status'=>$filters['status'],'marketing'=>$filters['marketing']?'1':'','per_page'=>$filters['per_page']];
$pageUrl = static fn(int $page): string => url('admin/customers?' . http_build_query(array_filter([...$baseQuery,'page'=>$page], static fn($value)=>$value!=='')));
?>
<section class="admin-page-head customer-page-head"><div><span class="eyebrow">Client relationships</span><h1>Customers</h1><p>Registered customers, online guests and identified POS clients in one searchable list.</p></div><?php if(can('customers.export')): ?><div class="customer-export-actions"><form method="post" action="<?= url('admin/customers/export') ?>"><?= csrf_field() ?><input type="hidden" name="scope" value="all"><button class="button button-secondary" type="submit"><i data-lucide="download"></i>Export all</button></form><form method="post" action="<?= url('admin/customers/export') ?>"><?= csrf_field() ?><input type="hidden" name="scope" value="marketing"><button class="button button-primary" type="submit"><i data-lucide="mail-check"></i>Marketing list</button></form></div><?php endif; ?></section>

<section class="customer-stat-grid">
  <article><span>Customer records</span><strong><?= number_format((int)$summary['customers']) ?></strong><i data-lucide="contact-round"></i></article>
  <article><span>Active customers</span><strong><?= number_format((int)$summary['active']) ?></strong><i data-lucide="user-round-check"></i></article>
  <article><span>Marketing approved</span><strong><?= number_format((int)$summary['marketing']) ?></strong><i data-lucide="messages-square"></i></article>
  <article><span>Known-customer sales</span><strong><?= money((int)$summary['lifetime_value_cents']) ?></strong><i data-lucide="badge-dollar-sign"></i></article>
</section>

<section class="admin-panel">
  <form class="admin-toolbar customer-toolbar" method="get">
    <div class="admin-filter-form"><label class="admin-search"><i data-lucide="search"></i><input type="search" name="q" value="<?= e($filters['q']) ?>" placeholder="Search name, phone, email, city or ZIP"><?php if($filters['q']!==''): ?><a href="<?= url('admin/customers') ?>" aria-label="Clear search"><i data-lucide="x"></i></a><?php endif; ?></label><label class="admin-filter-field"><span>Status</span><select name="status"><option value="">All customers</option><option value="active" <?= $filters['status']==='active'?'selected':'' ?>>Active</option><option value="inactive" <?= $filters['status']==='inactive'?'selected':'' ?>>Inactive</option></select></label><label class="admin-filter-field"><span>Contact list</span><select name="marketing"><option value="">All contacts</option><option value="1" <?= $filters['marketing']?'selected':'' ?>>Marketing approved</option></select></label><label class="admin-filter-field admin-page-size"><span>Show</span><select name="per_page"><?php foreach([20,50,100] as $size): ?><option value="<?= $size ?>" <?= $filters['per_page']===$size?'selected':'' ?>><?= $size ?></option><?php endforeach; ?></select></label><button class="button button-primary admin-filter-submit" type="submit">Find customers</button></div><span class="admin-result-count"><?= number_format($pagination['total']) ?> found</span>
  </form>
  <?php if($customers): ?><div class="admin-table-wrap responsive-table-wrap"><table class="admin-table customer-table responsive-card-table"><thead><tr><th>Customer</th><th>Contact</th><th>Location</th><th>Orders</th><th>Lifetime sales</th><th>Last order</th><th></th></tr></thead><tbody><?php foreach($customers as $customer): ?><tr><td data-primary><div class="customer-cell"><span><?= e(strtoupper(mb_substr($customer['name'],0,1))) ?></span><div><strong><?= e($customer['name']) ?></strong><small><?= (int)$customer['marketing_opt_in']===1?'Marketing approved':'Operational contact' ?> · <?= e(ucfirst($customer['status'])) ?></small></div></div></td><td data-label="Contact"><strong><?= e($customer['phone'] ?: 'No phone') ?></strong><small><?= e($customer['email'] ?: 'No email') ?></small></td><td data-label="Location"><strong><?= e($customer['city'] ?: 'Not provided') ?></strong><small><?= e(trim(($customer['state']?:'').' '.($customer['postal_code']?:'')) ?: 'No address') ?></small></td><td data-label="Orders"><strong><?= (int)$customer['order_count'] ?></strong><small><?= (int)$customer['pos_orders'] ?> POS · <?= (int)$customer['online_orders'] ?> online</small></td><td data-label="Lifetime"><strong><?= money((int)$customer['lifetime_value_cents']) ?></strong></td><td data-label="Last order"><?= $customer['last_order_at']?e(date('M j, Y',strtotime($customer['last_order_at']))):'No order' ?></td><td data-action><a class="button button-secondary button-small" href="<?= url('admin/customers/'.$customer['id']) ?>">Open customer<i data-lucide="chevron-right"></i></a></td></tr><?php endforeach; ?></tbody></table></div><?php else: ?><div class="empty-state small"><i data-lucide="contact-round"></i><h3>No customers matched</h3><p>Try a broader search or clear the filters.</p></div><?php endif; ?>
  <?php if($pagination['pages']>1): ?><nav class="admin-pagination" aria-label="Customer pages"><?php if($pagination['page']>1): ?><a class="button button-small button-secondary" href="<?= e($pageUrl($pagination['page']-1)) ?>">Previous</a><?php else: ?><span></span><?php endif; ?><span>Page <?= $pagination['page'] ?> of <?= $pagination['pages'] ?></span><?php if($pagination['page']<$pagination['pages']): ?><a class="button button-small button-secondary" href="<?= e($pageUrl($pagination['page']+1)) ?>">Next</a><?php endif; ?></nav><?php endif; ?>
</section>
