<section class="admin-page-head"><div><a class="back-link" href="<?= url('admin/customers') ?>"><i data-lucide="arrow-left"></i>Customers</a><span class="eyebrow">Private customer data</span><h1>Import customers</h1><p>Upload an Excel-compatible CSV, preview every match, then confirm. Existing notes and order history are never overwritten.</p></div><a class="button button-secondary" href="<?= url('admin/customers/import/template') ?>"><i data-lucide="download"></i>Download template</a></section>
<?php if (!$preview): ?>
<section class="admin-panel"><form method="post" enctype="multipart/form-data" class="form-grid"><?= csrf_field() ?><label class="full">Customer CSV<input type="file" name="customer_file" accept=".csv,text/csv" required><small>Maximum 2 MB and 5,000 rows. Export as CSV from Excel. Formula-like cells are rejected.</small></label><button class="button button-primary" type="submit"><i data-lucide="scan-search"></i>Securely preview import</button></form></section>
<?php else: ?>
<section class="admin-panel"><div class="panel-head"><div><span class="eyebrow">Review before import</span><h2><?= number_format($preview['total']) ?> valid rows</h2></div><span class="status-pill">Showing first <?= count($preview['rows']) ?></span></div>
<?php if ($preview['errors']): ?><div class="flash flash-warning"><strong>Review notes:</strong><br><?= nl2br(e(implode("\n", $preview['errors']))) ?></div><?php endif; ?>
<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Action</th><th>Name</th><th>Contact</th><th>Location</th><th>Marketing</th></tr></thead><tbody><?php foreach($preview['rows'] as $row): ?><tr><td><span class="status-pill"><?= e(ucfirst($row['_action'])) ?></span></td><td><strong><?= e($row['name']) ?></strong></td><td><?= e($row['email'] ?: $row['phone']) ?></td><td><?= e(trim($row['city'].' '.$row['state'].' '.$row['zip'])) ?></td><td><?= $row['marketing_opt_in']==='yes'?'Explicit consent':'No opt-in' ?></td></tr><?php endforeach; ?></tbody></table></div>
<div class="customer-export-actions"><form method="post" action="<?= url('admin/customers/import/confirm') ?>"><?= csrf_field() ?><button class="button button-primary" type="submit"><i data-lucide="user-round-check"></i>Confirm import</button></form><form method="post" action="<?= url('admin/customers/import/cancel') ?>"><?= csrf_field() ?><button class="button button-secondary" type="submit">Cancel and delete preview</button></form></div></section>
<?php endif; ?>
