<a class="back-link admin-back-link" href="<?= url('admin/customers') ?>"><i data-lucide="arrow-left"></i>Back to customers</a>
<section class="admin-page-head customer-profile-head"><div><span class="eyebrow">Customer profile</span><h1><?= e($customer['name']) ?></h1><p><?= e($customer['phone'] ?: 'No phone') ?> · <?= e($customer['email'] ?: 'No email') ?></p></div><span class="status-pill status-<?= e($customer['status']) ?>"><?= e(ucfirst($customer['status'])) ?></span></section>

<section class="customer-profile-stats">
  <article><span>Lifetime sales</span><strong><?= money((int)$customer['lifetime_value_cents']) ?></strong></article>
  <article><span>Orders</span><strong><?= number_format((int)$customer['order_count']) ?></strong></article>
  <article><span>Average sale</span><strong><?= money((int)$customer['average_order_cents']) ?></strong></article>
  <article><span>Last order</span><strong><?= $customer['last_order_at']?e(date('M j, Y',strtotime($customer['last_order_at']))):'None' ?></strong></article>
</section>

<section class="customer-profile-grid">
  <form method="post" class="admin-panel customer-profile-form">
    <?= csrf_field() ?><div class="panel-head"><div><span class="eyebrow">Client record</span><h2>Contact and preferences</h2></div><?php if((int)$customer['marketing_opt_in']===1): ?><span class="status-pill status-active">Marketing approved</span><?php endif; ?></div>
    <div class="form-grid"><label>Name<input name="name" value="<?= e($customer['name']) ?>" required <?= can('customers.edit')?'':'readonly' ?>></label><label>Phone<input type="tel" name="phone" value="<?= e($customer['phone']) ?>" <?= can('customers.edit')?'':'readonly' ?>></label><label class="full">Email<input type="email" name="email" value="<?= e($customer['email']) ?>" <?= can('customers.edit')?'':'readonly' ?>></label><label class="full">Street address<input name="address1" value="<?= e($customer['address1']) ?>" <?= can('customers.edit')?'':'readonly' ?>></label><label class="full">Apartment or suite<input name="address2" value="<?= e($customer['address2']) ?>" <?= can('customers.edit')?'':'readonly' ?>></label><label>City<input name="city" value="<?= e($customer['city']) ?>" <?= can('customers.edit')?'':'readonly' ?>></label><label>State<input name="state" value="<?= e($customer['state']?:'NY') ?>" <?= can('customers.edit')?'':'readonly' ?>></label><label>ZIP<input name="postal_code" value="<?= e($customer['postal_code']) ?>" <?= can('customers.edit')?'':'readonly' ?>></label><label>Status<select name="status" <?= can('customers.edit')?'':'disabled' ?>><option value="active" <?= $customer['status']==='active'?'selected':'' ?>>Active</option><option value="inactive" <?= $customer['status']==='inactive'?'selected':'' ?>>Inactive</option></select></label><label class="check-row full"><input type="checkbox" name="marketing_opt_in" value="1" <?= (int)$customer['marketing_opt_in']===1?'checked':'' ?> <?= can('customers.edit')?'':'disabled' ?>><span>Customer agreed to receive store updates and promotions.</span></label><label class="full">Private staff notes<textarea name="private_notes" rows="5" <?= can('customers.edit')?'':'readonly' ?>><?= e($customer['private_notes']) ?></textarea></label></div>
    <?php if(can('customers.edit')): ?><button class="button button-primary" type="submit"><i data-lucide="save"></i>Save customer</button><?php endif; ?><p class="form-hint"><i data-lucide="shield-check"></i>Changing this profile never rewrites historical orders or receipts.</p>
  </form>
  <aside class="customer-profile-side">
    <article class="admin-panel"><div class="panel-head"><div><span class="eyebrow">Preferences</span><h2>Most purchased</h2></div></div><?php if($products): ?><div class="report-simple-list"><?php foreach($products as $product): ?><div><span><strong><?= e($product['product_name']) ?></strong><small><?= e($product['variant_label']) ?> · <?= (int)$product['units'] ?> items</small></span><b><?= money((int)$product['revenue']) ?></b></div><?php endforeach; ?></div><?php else: ?><p class="report-empty">No completed purchases yet.</p><?php endif; ?></article>
    <article class="admin-panel"><div class="panel-head"><div><span class="eyebrow">Delivery history</span><h2>Known addresses</h2></div></div><?php if($addresses): ?><div class="customer-address-list"><?php foreach($addresses as $address): ?><div><i data-lucide="map-pin"></i><span><strong><?= e($address['address1']) ?></strong><small><?= e(trim(($address['address2']?$address['address2'].', ':'').$address['city'].', '.$address['state'].' '.$address['postal_code'])) ?></small></span></div><?php endforeach; ?></div><?php else: ?><p class="report-empty">No delivery address recorded.</p><?php endif; ?></article>
  </aside>
</section>

<section class="admin-panel customer-order-history"><div class="panel-head"><div><span class="eyebrow">Complete history</span><h2>Orders</h2></div><strong><?= count($orders) ?> total</strong></div><?php if($orders): ?><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Order</th><th>Source</th><th>Status</th><th>Payment</th><th>Total</th><th></th></tr></thead><tbody><?php foreach($orders as $order): ?><tr><td><strong><?= e($order['order_number']) ?></strong><small><?= e(date('M j, Y · g:i A',strtotime($order['created_at']))) ?></small></td><td><?= ($order['order_source']??'online')==='pos'?'POS':'Online' ?></td><td><span class="status-pill status-<?= e($order['status']) ?>"><?= e(ucwords(str_replace('_',' ',$order['status']))) ?></span></td><td><?= e(ucwords(str_replace('_',' ',$order['payment_method']))) ?></td><td><strong><?= money((int)$order['total_cents']) ?></strong></td><td><a class="icon-button" href="<?= url('admin/orders/'.$order['id']) ?>"><i data-lucide="chevron-right"></i></a></td></tr><?php endforeach; ?></tbody></table></div><?php else: ?><div class="empty-state small"><i data-lucide="package-open"></i><h3>No orders linked</h3></div><?php endif; ?></section>
