<section class="admin-page-head"><div><span class="eyebrow">Today at a glance</span><h1><?= e($title) ?></h1><p>Use the tools your account is approved to manage.</p></div><div class="button-row"><?php if (can('pos.access')): ?><a class="button button-primary" href="<?= url('admin/pos') ?>"><i data-lucide="tablet-smartphone"></i>Open POS</a><?php endif; ?><?php if (can('products.create')): ?><a class="button button-secondary" href="<?= url('admin/products/new') ?>"><i data-lucide="plus"></i>Add product</a><?php endif; ?></div></section>

<?php if (can('orders.view') || can('products.view')): ?><section class="stat-grid"><?php if (can('orders.view')): ?><article><span>Orders needing attention</span><strong><?= $counts['attention'] ?></strong><i data-lucide="bell-ring"></i></article><?php endif; ?><?php if (can('products.view')): ?><article><span>Active catalog</span><strong><?= $counts['products'] ?></strong><i data-lucide="package-open"></i></article><article><span>Low stock options</span><strong><?= $counts['low_stock'] ?></strong><i data-lucide="triangle-alert"></i></article><article><span>Sold out options</span><strong><?= $counts['sold_out'] ?></strong><i data-lucide="circle-off"></i></article><?php endif; ?></section><?php endif; ?>

<?php if($sales): ?><section class="report-kpi-grid dashboard-sales-strip"><article><span><i data-lucide="banknote"></i>Sales today</span><strong><?= money((int)$sales['revenue']) ?></strong></article><article><span><i data-lucide="receipt-text"></i>Paid orders</span><strong><?= (int)$sales['orders'] ?></strong></article><article><span><i data-lucide="package-check"></i>Items sold</span><strong><?= (int)$sales['units'] ?></strong></article><article><span><i data-lucide="circle-dollar-sign"></i>Average sale</span><strong><?= money((int)$sales['average']) ?></strong></article><a class="dashboard-report-link" href="<?= url('admin/reports?range=today') ?>"><span>Open full report</span><i data-lucide="arrow-up-right"></i></a></section><?php endif; ?>

<?php if (can('orders.view')): ?><section class="admin-panel"><div class="panel-head"><div><span class="eyebrow">Latest activity</span><h2>Recent orders</h2></div><a href="<?= url('admin/orders') ?>">View all<i data-lucide="arrow-right"></i></a></div><?php if($orders): ?><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Order</th><th>Customer</th><th>Source</th><th>Status</th><th>Total</th><th></th></tr></thead><tbody><?php foreach($orders as $order): ?><tr><td><strong><?= e($order['order_number']) ?></strong><small><?= e(date('M j · g:i A',strtotime($order['created_at']))) ?></small></td><td><?= e($order['customer_name']) ?></td><td><?= ($order['order_source'] ?? 'online') === 'pos' ? 'POS' : e(ucfirst($order['fulfillment'])) ?></td><td><span class="status-pill status-<?= e($order['status']) ?>"><?= e(ucwords(str_replace('_',' ',$order['status']))) ?></span></td><td><?= money((int)$order['total_cents']) ?></td><td><a class="icon-button" href="<?= url('admin/orders/'.$order['id']) ?>" aria-label="Open order"><i data-lucide="chevron-right"></i></a></td></tr><?php endforeach; ?></tbody></table></div><?php else: ?><div class="empty-state small"><i data-lucide="package-open"></i><h3>No orders yet</h3></div><?php endif; ?></section><?php endif; ?>

<section class="admin-grid-two"><?php if (can('settings.manage')): ?><article class="admin-panel"><div class="panel-head"><div><span class="eyebrow">Operations</span><h2>Store controls</h2></div><a href="<?= url('admin/settings') ?>">Manage</a></div><div class="setting-summary"><span><i data-lucide="<?= setting('ordering_enabled')?'check-circle-2':'pause-circle' ?>"></i>Online ordering <b><?= setting('ordering_enabled')?'On':'Off' ?></b></span><span><i data-lucide="<?= setting('pos_enabled')?'check-circle-2':'pause-circle' ?>"></i>POS register <b><?= setting('pos_enabled')?'On':'Off' ?></b></span><span><i data-lucide="truck"></i>Delivery <b><?= setting('delivery_enabled')?'On':'Off' ?></b></span></div></article><?php endif; ?><article class="admin-panel"><div class="panel-head"><div><span class="eyebrow">Your access</span><h2>Available tools</h2></div></div><div class="setting-summary"><?php foreach (\App\Auth::permissionDefinitions() as $permission => $label): if (!can($permission)) continue; ?><span><i data-lucide="check-circle-2"></i><?= e($label) ?></span><?php endforeach; ?></div></article></section>
