<section class="admin-page-head pos-page-head"><div><span class="eyebrow">In-store checkout</span><h1>Point of sale</h1><p>Search the shared catalog, verify ID, and complete a walk-in sale.</p></div><span class="pos-live-status"><i data-lucide="<?= setting('pos_enabled',true) ? 'wifi' : 'pause-circle' ?>"></i><?= setting('pos_enabled',true) ? 'Register ready' : 'POS disabled' ?></span></section>

<?php if (!setting('pos_enabled', true)): ?><div class="admin-panel pos-disabled"><i data-lucide="pause-circle"></i><div><strong>The POS is disabled</strong><p>An owner can enable it under Store settings.</p></div><?php if (can('settings.manage')): ?><a class="button button-secondary" href="<?= url('admin/settings') ?>">Open settings</a><?php endif; ?></div><?php endif; ?>

<section class="pos-workspace" data-pos-app data-pos-enabled="<?= setting('pos_enabled',true) ? '1' : '0' ?>" data-can-complete="<?= $canComplete ? '1' : '0' ?>" data-tax-enabled="<?= setting('pos_tax_enabled',false) ? '1' : '0' ?>" data-tax-rate="<?= e((string) setting('pos_tax_rate','0')) ?>" data-discount-enabled="<?= setting('pos_manual_discount_enabled',false) && $canDiscount ? '1' : '0' ?>">
  <div class="pos-catalog-panel">
    <div class="pos-catalog-tools"><label class="pos-search"><i data-lucide="search"></i><input type="search" placeholder="Search product, brand, option or flavor" data-pos-search autocomplete="off"></label><span><b data-pos-visible-count><?= count($catalog) ?></b> products</span></div>
    <div class="pos-category-rail" data-pos-categories><button type="button" class="active" data-pos-category="">All</button><?php foreach ($categories as $category): ?><button type="button" data-pos-category="<?= e($category['slug']) ?>"><?= e($category['name']) ?></button><?php endforeach; ?></div>
    <div class="pos-product-grid" data-pos-products>
      <?php foreach ($catalog as $product): $searchText = strtolower(trim(($product['name'] ?? '') . ' ' . ($product['brand'] ?? '') . ' ' . implode(' ', array_map(static fn($v) => ($v['label'] ?? '') . ' ' . ($v['flavors'] ?? '') . ' ' . ($v['sku'] ?? ''), $product['variants'])))); ?>
        <article class="pos-product-card" data-pos-product data-category="<?= e($product['category_slug']) ?>" data-search="<?= e($searchText) ?>">
          <div class="pos-product-summary"><?php if ($product['image_path']): ?><img src="<?= url($product['image_path']) ?>" alt=""><?php else: ?><span class="pos-image-fallback"><i data-lucide="package-open"></i></span><?php endif; ?><div><small><?= e($product['brand'] ?: $product['category_name']) ?></small><h2><?= e($product['name']) ?></h2><span><?= e($product['category_name']) ?><?= $product['strain_type'] ? ' · ' . e($product['strain_type']) : '' ?></span></div></div>
          <div class="pos-variant-list"><?php foreach ($product['variants'] as $variant): $price = (int) ($variant['sale_price_cents'] ?: $variant['price_cents']); ?><button type="button" data-pos-add data-variant-id="<?= (int) $variant['id'] ?>" data-product-name="<?= e($product['name']) ?>" data-variant-label="<?= e($variant['label']) ?>" data-price="<?= $price ?>" data-stock="<?= $variant['stock_quantity'] === null ? '' : (int) $variant['stock_quantity'] ?>"><span><strong><?= e($variant['label']) ?></strong><?php if ($variant['flavors']): ?><small><?= e($variant['flavors']) ?></small><?php endif; ?></span><b><?= money($price) ?></b><i data-lucide="plus"></i></button><?php endforeach; ?></div>
        </article>
      <?php endforeach; ?>
    </div>
    <div class="empty-state small pos-no-results" data-pos-no-results hidden><i data-lucide="search-x"></i><h3>No matching products</h3><p>Try a different search or category.</p></div>
  </div>

  <aside class="admin-panel pos-cart-panel">
    <form method="post" data-pos-form>
      <?= csrf_field() ?><input type="hidden" name="cart_json" data-pos-cart-json>
      <div class="pos-cart-head"><div><span class="step-label">Current sale</span><h2>Cart <small data-pos-cart-count>0</small></h2></div><button type="button" class="button button-quiet button-small" data-pos-clear>Clear</button></div>
      <div class="pos-cart-items" data-pos-cart-items><div class="empty-cart"><i data-lucide="shopping-basket"></i><strong>Cart is empty</strong><p>Tap a product option to add it.</p></div></div>
      <div class="pos-totals"><div><span>Subtotal</span><strong data-pos-subtotal>$0.00</strong></div><div data-pos-discount-row hidden><span>Discount</span><strong data-pos-discount>−$0.00</strong></div><div data-pos-tax-row <?= setting('pos_tax_enabled',false) ? '' : 'hidden' ?>><span>Tax <small><?= e((string) setting('pos_tax_rate','0')) ?>%</small></span><strong data-pos-tax>$0.00</strong></div><div class="pos-total"><span>Total</span><strong data-pos-total>$0.00</strong></div></div>
      <?php if (setting('pos_manual_discount_enabled',false) && $canDiscount): ?><label>Manual discount (%)<input type="number" name="discount_percent" min="0" max="<?= (int) setting('pos_max_discount_percent',20) ?>" step="0.01" value="0" data-pos-discount-input></label><?php elseif (setting('pos_manual_discount_enabled',false)): ?><p class="form-hint"><i data-lucide="lock-keyhole"></i>Your account cannot apply manual discounts.</p><?php endif; ?>
      <details class="pos-customer-details"><summary>Customer details <small>Optional</small></summary><div class="form-grid"><label>Name<input name="customer_name" autocomplete="name" placeholder="Walk-in customer"></label><label>Phone<input type="tel" name="customer_phone" autocomplete="tel"></label><label class="full">Email receipt to<input type="email" name="customer_email" autocomplete="email" <?= setting('pos_email_receipt_enabled',true) ? '' : 'disabled' ?>></label><label class="full">Notes<textarea name="customer_notes" rows="2"></textarea></label></div></details>
      <fieldset class="pos-payment-options"><legend>Payment</legend><?php if (setting('pos_cash_enabled',true)): ?><label><input type="radio" name="payment_method" value="cash" checked><span><i data-lucide="banknote"></i><strong>Cash</strong></span></label><?php endif; ?><?php if (setting('pos_external_card_enabled',true)): ?><label><input type="radio" name="payment_method" value="external_card" <?= setting('pos_cash_enabled',true) ? '' : 'checked' ?>><span><i data-lucide="credit-card"></i><strong>External terminal</strong><small>Card data is not stored</small></span></label><?php endif; ?></fieldset>
      <label class="pos-age-check"><input type="checkbox" name="age_verified" value="1" required><span><i data-lucide="badge-check"></i><strong>ID checked — customer is 21+</strong><small>Required before completing the sale.</small></span></label>
      <button class="button button-primary button-large button-wide" type="submit" data-pos-submit disabled><?= $canComplete ? 'Complete sale' : 'Sale approval required' ?><i data-lucide="check-circle-2"></i></button>
      <?php if (!$canComplete): ?><p class="form-hint"><i data-lucide="lock-keyhole"></i>Your account can prepare carts but cannot approve purchases.</p><?php endif; ?>
    </form>
  </aside>
</section>
