<section class="admin-page-head"><div><span class="eyebrow">Owner only</span><h1>Security center</h1><p>Account protection, production checks and security-sensitive history.</p></div><a class="button button-primary" href="<?= url('account/security') ?>"><i data-lucide="shield-check"></i>My security</a></section>

<section class="customer-stat-grid security-check-grid">
  <?php foreach($checks as $label=>$ok): ?><article><span><?= e($label) ?></span><strong><?= $ok?'Ready':'Action needed' ?></strong><i data-lucide="<?= $ok?'shield-check':'shield-alert' ?>"></i></article><?php endforeach; ?>
</section>

<section class="admin-panel"><div class="panel-head"><div><span class="eyebrow">Access posture</span><h2>Staff accounts</h2></div><a href="<?= url('admin/staff') ?>" class="button button-secondary">Manage staff</a></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Account</th><th>Role</th><th>MFA</th><th>Password</th><th>Last login</th></tr></thead><tbody><?php foreach($staffSecurity as $member): ?><tr><td><strong><?= e($member['name']) ?></strong><small><?= e($member['email']) ?></small></td><td><?= e(ucfirst($member['role'])) ?></td><td><span class="status-pill <?= $member['mfa_enabled_at']?'status-active':'' ?>"><?= $member['mfa_enabled_at']?'Enabled':'Not enabled' ?></span></td><td><?= $member['must_change_password']?'Temporary':'Set' ?></td><td><?= $member['last_login_at']?e(date('M j, Y g:i A',strtotime($member['last_login_at']))):'Never' ?></td></tr><?php endforeach; ?></tbody></table></div></section>

<section class="admin-panel"><div class="panel-head"><div><span class="eyebrow">Audit history</span><h2>Recent security events</h2></div><span class="status-pill">Last 100</span></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Time</th><th>Event</th><th>Account</th><th>IP</th></tr></thead><tbody><?php foreach($events as $event): ?><tr><td><?= e(date('M j, Y g:i A',strtotime($event['created_at']))) ?></td><td><?= e(ucwords(str_replace(['.','_'],' ',$event['action']))) ?></td><td><?= e($event['user_name'] ?: 'Unknown / public') ?></td><td><?= e($event['ip_address'] ?: 'Unknown') ?></td></tr><?php endforeach; ?></tbody></table></div></section>
