<section class="admin-page-head"><div><span class="eyebrow">Operations</span><h1>Store settings</h1><p>Turn storefront and point-of-sale features on or off without changing code.</p></div></section>
<form method="post" class="settings-layout">
  <?= csrf_field() ?>
  <div class="settings-main">
    <section class="admin-panel settings-section"><div><span class="step-label">Store status</span><h2>Availability</h2></div><div class="toggle-grid"><?php foreach(['ordering_enabled'=>'Online ordering','pickup_enabled'=>'Pickup','delivery_enabled'=>'Delivery','same_day_enabled'=>'Same-day orders','scheduled_enabled'=>'Scheduled orders','guest_checkout_enabled'=>'Guest checkout','registration_enabled'=>'Customer registration','manual_confirmation'=>'Owner confirmation'] as $key=>$label): ?><label class="toggle-row"><span><strong><?= e($label) ?></strong><small>Enable or pause this feature.</small></span><input type="checkbox" name="<?= e($key) ?>" value="1" <?= setting($key)?'checked':'' ?>><i></i></label><?php endforeach; ?></div></section>

    <section class="admin-panel settings-section pos-settings-section">
      <div><span class="step-label">In-store checkout</span><h2>Point of sale</h2><p>The POS records cash or an external terminal result. It never stores card numbers.</p></div>
      <div class="toggle-grid"><?php foreach(['pos_enabled'=>'Enable POS register','pos_cash_enabled'=>'Accept cash','pos_external_card_enabled'=>'Record external card terminal','pos_tax_enabled'=>'Add POS tax','pos_print_receipt_enabled'=>'Offer printed receipts','pos_email_receipt_enabled'=>'Offer emailed receipts','pos_manual_discount_enabled'=>'Allow manual discounts','customer_capture_enabled'=>'Prioritize customer capture','marketing_opt_in_enabled'=>'Offer marketing opt-in'] as $key=>$label): ?><label class="toggle-row"><span><strong><?= e($label) ?></strong><small>Change this independently at any time.</small></span><input type="checkbox" name="<?= e($key) ?>" value="1" <?= setting($key)?'checked':'' ?>><i></i></label><?php endforeach; ?></div>
      <div class="form-grid pos-setting-values"><label>Tax rate (%)<input type="number" min="0" max="30" step="0.001" name="pos_tax_rate" value="<?= e((string) setting('pos_tax_rate','0')) ?>"></label><label>Maximum manual discount (%)<input type="number" min="0" max="100" step="1" name="pos_max_discount_percent" value="<?= (int) setting('pos_max_discount_percent',20) ?>"></label></div>
    </section>

    <section class="admin-panel settings-section"><div><span class="step-label">Reporting</span><h2>Business time and location</h2><p>Sales ranges and charts use this timezone. Existing order timestamps are never rewritten.</p></div><div class="form-grid"><label>Business city<input name="business_city" value="<?= e((string) setting('business_city','Long Island, NY')) ?>" placeholder="Long Island, NY"></label><label>Reporting timezone<select name="report_timezone"><?php foreach(['America/New_York'=>'Eastern Time','America/Chicago'=>'Central Time','America/Denver'=>'Mountain Time','America/Los_Angeles'=>'Pacific Time','America/Phoenix'=>'Arizona Time','America/Anchorage'=>'Alaska Time','Pacific/Honolulu'=>'Hawaii Time'] as $zone=>$label): ?><option value="<?= e($zone) ?>" <?= setting('report_timezone','America/New_York')===$zone?'selected':'' ?>><?= e($label) ?> — <?= e($zone) ?></option><?php endforeach; ?></select></label></div></section>

    <section class="admin-panel settings-section"><div><span class="step-label">Business details</span><h2>Store information</h2></div><div class="form-grid"><label>Store name<input name="store_name" value="<?= e(setting('store_name')) ?>"></label><label>Status<select name="store_status"><option value="open" <?= setting('store_status')==='open'?'selected':'' ?>>Open</option><option value="paused" <?= setting('store_status')==='paused'?'selected':'' ?>>Paused</option><option value="closed" <?= setting('store_status')==='closed'?'selected':'' ?>>Closed</option></select></label><label>Phone<input name="store_phone" value="<?= e(setting('store_phone')) ?>"></label><label>Email<input type="email" name="store_email" value="<?= e(setting('store_email')) ?>"></label><label class="full">Tagline<input name="store_tagline" value="<?= e(setting('store_tagline')) ?>"></label><label class="full">Announcement<input name="announcement" value="<?= e(setting('announcement')) ?>"></label><label>Hours<input name="hours" value="<?= e(setting('hours')) ?>"></label><label>License number<input name="license_number" value="<?= e(setting('license_number')) ?>"></label><label class="full">Required warning<textarea name="required_warning" rows="3"><?= e(setting('required_warning')) ?></textarea></label></div></section>

    <section class="admin-panel settings-section"><div><span class="step-label">Fulfillment</span><h2>Locations, areas and minimums</h2></div><div class="form-grid"><label class="full">Pickup address<input name="pickup_address" value="<?= e(setting('pickup_address')) ?>" placeholder="Hidden until pickup is approved"></label><label>Delivery areas<input name="service_areas" value="<?= e(setting('service_areas')) ?>"></label><label>Extended areas<input name="extended_areas" value="<?= e(setting('extended_areas')) ?>"></label><label>Pickup minimum ($)<input type="number" step="0.01" name="pickup_minimum_cents" value="<?= number_format((int)setting('pickup_minimum_cents')/100,2,'.','') ?>"></label><label>Delivery minimum ($)<input type="number" step="0.01" name="delivery_minimum_cents" value="<?= number_format((int)setting('delivery_minimum_cents')/100,2,'.','') ?>"></label><label>Extended-area minimum ($)<input type="number" step="0.01" name="extended_delivery_minimum_cents" value="<?= number_format((int)setting('extended_delivery_minimum_cents')/100,2,'.','') ?>"></label><label>Delivery fee ($)<input type="number" step="0.01" name="delivery_fee_cents" value="<?= number_format((int)setting('delivery_fee_cents')/100,2,'.','') ?>"></label></div></section>

    <section class="admin-panel settings-section"><div><span class="step-label">Online payments</span><h2>Allowed storefront methods</h2><p>Online card or bank payments remain unavailable until an approved provider is installed and tested.</p></div><div class="toggle-grid"><?php foreach(['pay_at_pickup_enabled'=>'Pay at pickup','manual_prepaid_enabled'=>'Prepaid arrangement'] as $key=>$label): ?><label class="toggle-row"><span><strong><?= e($label) ?></strong><small>Control availability at customer checkout.</small></span><input type="checkbox" name="<?= e($key) ?>" value="1" <?= setting($key)?'checked':'' ?>><i></i></label><?php endforeach; ?></div><div class="provider-locked"><i data-lucide="lock-keyhole"></i><span><strong>Online card or bank payment</strong><small>Requires a licensed, approved cannabis payment provider.</small></span></div></section>
    <section class="admin-panel settings-section"><div><span class="step-label">Receipts and campaigns</span><h2>Email delivery</h2><p>Use a mailbox on your domain. Marketing remains locked until sender, DNS, license and address checks are complete.</p></div><div class="toggle-grid"><?php foreach(['email_enabled'=>'Enable queued email delivery','email_order_confirmation_enabled'=>'Email online order confirmations','marketing_campaigns_enabled'=>'Allow approved marketing campaigns','email_dns_verified'=>'SPF, DKIM and DMARC are verified'] as $key=>$label): ?><label class="toggle-row"><span><strong><?= e($label) ?></strong><small>Campaigns still need a separate approval.</small></span><input type="checkbox" name="<?= e($key) ?>" value="1" <?= setting($key)?'checked':'' ?>><i></i></label><?php endforeach; ?></div><div class="form-grid"><label>From name<input name="email_from_name" value="<?= e(setting('email_from_name')) ?>"></label><label>From address<input type="email" name="email_from_address" value="<?= e(setting('email_from_address')) ?>" placeholder="receipts@yourdomain.com"></label><label>Reply-to<input type="email" name="email_reply_to" value="<?= e(setting('email_reply_to')) ?>"></label><label>Monthly draft day<input type="number" min="1" max="28" name="marketing_campaign_day" value="<?= (int)setting('marketing_campaign_day',1) ?>"></label><label class="full">Business mailing address<input name="marketing_physical_address" value="<?= e(setting('marketing_physical_address')) ?>"></label><label class="full">HOPEline disclosure<input name="marketing_hopeline" value="<?= e(setting('marketing_hopeline')) ?>"></label></div></section>
    <section class="admin-panel settings-section"><div><span class="step-label">Campaign identity</span><h2>Marketing sender</h2><p>Approved product updates use a separate sender from transactional receipts.</p></div><div class="form-grid"><label>Marketing From name<input name="marketing_from_name" value="<?= e(setting('marketing_from_name','THC LI Updates')) ?>"></label><label>Marketing From address<input type="email" name="marketing_from_address" value="<?= e(setting('marketing_from_address','updates@thc-li.com')) ?>"></label><label class="full">Marketing reply-to<input type="email" name="marketing_reply_to" value="<?= e(setting('marketing_reply_to','receipts@thc-li.com')) ?>"></label></div></section>
    <section class="admin-panel settings-section"><div><span class="step-label">Owner notifications</span><h2>New online orders</h2><p>Operational alerts go to a private staff inbox. Full delivery details remain inside the secured Admin area.</p></div><div class="form-grid"><label class="full">Order notification email<input type="email" name="order_notification_email" value="<?= e(setting('order_notification_email','orders@thc-li.com')) ?>"></label></div></section>
    <section class="admin-panel settings-section"><div><span class="step-label">Staff security</span><h2>Require two-factor authentication</h2><p>Enroll your own authenticator under Security first. When enabled, every owner, manager and staff account must finish MFA setup before using Admin.</p></div><label class="toggle-row"><span><strong>Require MFA for all staff</strong><small>Recommended after the owner has enrolled successfully.</small></span><input type="checkbox" name="staff_mfa_required" value="1" <?= setting('staff_mfa_required',false)?'checked':'' ?>><i></i></label><a class="button button-secondary" href="<?= url('account/security') ?>">Open my security settings</a></section>
  </div>
  <aside class="admin-panel settings-save"><h2>Save settings</h2><p>Changes affect new checkouts immediately. Existing receipts keep their original totals.</p><button class="button button-primary button-wide" type="submit">Save all settings<i data-lucide="save"></i></button><a class="button button-secondary button-wide" href="<?= can('pos.access') ? url('admin/pos') : url('') ?>"><?= can('pos.access') ? 'Open POS' : 'Preview storefront' ?></a></aside>
</form>
