<?php
declare(strict_types=1);

$appRoot = is_file(__DIR__ . '/../app/bootstrap.php') ? dirname(__DIR__) : dirname(__DIR__) . '/dispensary-app';
if (!is_file($appRoot . '/app/bootstrap.php')) {
    http_response_code(500);
    exit('Application files were not found. Check the cPanel deployment path.');
}
require $appRoot . '/app/bootstrap.php';

use App\Controller;
use App\Router;

$router = new Router();
$router->get('/', [Controller::class, 'home']);
$router->get('/menu', [Controller::class, 'menu']);
$router->get('/product/{slug}', [Controller::class, 'product']);
$router->get('/login', [Controller::class, 'login']);
$router->post('/login', [Controller::class, 'login']);
$router->get('/login/mfa', [Controller::class, 'loginMfa']);
$router->post('/login/mfa', [Controller::class, 'loginMfa']);
$router->get('/register', [Controller::class, 'register']);
$router->post('/register', [Controller::class, 'register']);
$router->post('/logout', [Controller::class, 'logout']);
$router->get('/account', [Controller::class, 'account']);
$router->get('/account/security', [Controller::class, 'accountSecurity']);
$router->post('/account/security/password', [Controller::class, 'accountSecurityPassword']);
$router->post('/account/security/mfa/start', [Controller::class, 'accountSecurityMfaStart']);
$router->post('/account/security/mfa/confirm', [Controller::class, 'accountSecurityMfaConfirm']);
$router->post('/account/security/mfa/disable', [Controller::class, 'accountSecurityMfaDisable']);
$router->get('/account/orders/{id}', [Controller::class, 'accountOrder']);
$router->post('/account/favorites/{id}', [Controller::class, 'favorite']);
$router->post('/account/addresses/{id}/delete', [Controller::class, 'deleteAddress']);
$router->get('/checkout', [Controller::class, 'checkout']);
$router->post('/checkout', [Controller::class, 'checkout']);
$router->get('/order/{number}/success', [Controller::class, 'orderSuccess']);
$router->get('/unsubscribe/{token}', [Controller::class, 'unsubscribe']);
$router->post('/unsubscribe/{token}', [Controller::class, 'unsubscribe']);
$router->get('/setup', [Controller::class, 'setup']);
$router->post('/setup', [Controller::class, 'setup']);
$router->get('/admin', [Controller::class, 'admin']);
$router->get('/admin/security', [Controller::class, 'adminSecurity']);
$router->get('/admin/reports', [Controller::class, 'adminReports']);
$router->get('/admin/customers', [Controller::class, 'adminCustomers']);
$router->get('/admin/customers/search', [Controller::class, 'adminCustomerSearch']);
$router->post('/admin/customers/export', [Controller::class, 'adminCustomersExport']);
$router->get('/admin/customers/import', [Controller::class, 'adminCustomersImport']);
$router->post('/admin/customers/import', [Controller::class, 'adminCustomersImport']);
$router->get('/admin/customers/import/template', [Controller::class, 'adminCustomersImportTemplate']);
$router->post('/admin/customers/import/confirm', [Controller::class, 'adminCustomersImportConfirm']);
$router->post('/admin/customers/import/cancel', [Controller::class, 'adminCustomersImportCancel']);
$router->get('/admin/customers/{id}', [Controller::class, 'adminCustomer']);
$router->post('/admin/customers/{id}', [Controller::class, 'adminCustomer']);
$router->get('/admin/products', [Controller::class, 'adminProducts']);
$router->get('/admin/products/new', static fn() => Controller::adminProduct());
$router->post('/admin/products/new', static fn() => Controller::adminProduct());
$router->get('/admin/products/{id}/edit', [Controller::class, 'adminProduct']);
$router->post('/admin/products/{id}/edit', [Controller::class, 'adminProduct']);
$router->post('/admin/products/{id}/archive', [Controller::class, 'adminProductArchive']);
$router->get('/admin/pos', [Controller::class, 'adminPos']);
$router->post('/admin/pos', [Controller::class, 'adminPos']);
$router->get('/admin/pos/receipt/{id}', [Controller::class, 'adminPosReceipt']);
$router->get('/admin/orders', [Controller::class, 'adminOrders']);
$router->get('/admin/orders/{id}', [Controller::class, 'adminOrder']);
$router->post('/admin/orders/{id}', [Controller::class, 'adminOrder']);
$router->post('/admin/orders/{id}/email-receipt', [Controller::class, 'adminOrderEmailReceipt']);
$router->get('/admin/email', [Controller::class, 'adminEmail']);
$router->post('/admin/email/campaigns', [Controller::class, 'adminEmailCampaignCreate']);
$router->post('/admin/email/campaigns/{id}/approve', [Controller::class, 'adminEmailCampaignApprove']);
$router->post('/admin/email/campaigns/{id}/cancel', [Controller::class, 'adminEmailCampaignCancel']);
$router->post('/admin/email/queue/run', [Controller::class, 'adminEmailQueueRun']);
$router->get('/admin/settings', [Controller::class, 'adminSettings']);
$router->post('/admin/settings', [Controller::class, 'adminSettings']);
$router->post('/admin/settings/email-test', [Controller::class, 'adminEmailTransportTest']);
$router->get('/admin/promotions', [Controller::class, 'adminPromotions']);
$router->post('/admin/promotions', [Controller::class, 'adminPromotions']);
$router->post('/admin/promotions/{id}/toggle', [Controller::class, 'adminPromotionToggle']);
$router->post('/admin/promotions/{id}/delete', [Controller::class, 'adminPromotionDelete']);
$router->get('/admin/staff', [Controller::class, 'adminStaff']);
$router->post('/admin/staff', [Controller::class, 'adminStaff']);
$router->post('/admin/staff/{id}', [Controller::class, 'adminStaffUpdate']);
$router->get('/health', [Controller::class, 'health']);
$router->dispatch($_SERVER['REQUEST_METHOD'], $_SERVER['REQUEST_URI']);
