<section class="page-intro container account-intro"><span class="eyebrow">Customer account</span><h1>Hello, <?= e(current_user()['name']) ?></h1><p>Your previous orders, saved products and addresses are kept together here.</p></section>
<section class="container account-grid">
  <div class="account-column">
    <div class="account-panel"><div class="section-heading compact"><div><h2>Order history</h2></div><a href="<?= url('menu') ?>">Shop again<i data-lucide="arrow-right"></i></a></div><?php if($orders): ?><div class="order-list"><?php foreach($orders as $order): ?><a class="order-row" href="<?= url('account/orders/'.$order['id']) ?>"><span class="order-icon"><i data-lucide="package"></i></span><span><strong><?= e($order['order_number']) ?></strong><small><?= e(date('M j, Y · g:i A',strtotime($order['created_at']))) ?> · <?= e(ucwords(str_replace('_',' ',$order['status']))) ?></small></span><b><?= money((int)$order['total_cents']) ?></b><i data-lucide="chevron-right"></i></a><?php endforeach; ?></div><?php else: ?><div class="empty-state small"><i data-lucide="package-open"></i><h3>No orders yet</h3><p>Your first confirmed order will appear here.</p><a class="button button-primary" href="<?= url('menu') ?>">Browse menu</a></div><?php endif; ?></div>
    <?php if($favorites): ?><div class="account-panel"><div class="section-heading compact"><div><h2>Favorites</h2></div></div><div class="favorite-grid"><?php foreach(array_slice($favorites,0,4) as $product) require APP_ROOT.'/app/Views/partials/product-card.php'; ?></div></div><?php endif; ?>
  </div>
  <aside class="account-column">
    <div class="account-panel profile-panel"><h2>Account details</h2><dl><div><dt>Name</dt><dd><?= e(current_user()['name']) ?></dd></div><div><dt>Email</dt><dd><?= e(current_user()['email']) ?></dd></div><div><dt>Phone</dt><dd><?= e(current_user()['phone'] ?: 'Not provided') ?></dd></div></dl><a class="button button-secondary button-wide" href="<?= url('account/security') ?>"><i data-lucide="shield-check"></i>Security settings</a><form method="post" action="<?= url('logout') ?>"><?= csrf_field() ?><button class="button button-secondary button-wide" type="submit">Sign out</button></form></div>
    <?php if($addresses): ?><div class="account-panel"><h2>Saved addresses</h2><div class="saved-addresses"><?php foreach($addresses as $address): ?><article><div><strong><?= e($address['label']?:'Delivery') ?></strong><small><?= e($address['address1'].', '.$address['city'].' '.$address['postal_code']) ?></small></div><form method="post" action="<?= url('account/addresses/'.$address['id'].'/delete') ?>"><?= csrf_field() ?><button class="icon-button" aria-label="Remove address"><i data-lucide="trash-2"></i></button></form></article><?php endforeach; ?></div></div><?php endif; ?>
  </aside>
</section>
